-- WORD BATTLE — room creation / room join fix
--
-- Run this file in the Supabase SQL Editor on an existing project. It is idempotent, so it can be
-- executed as often as needed. Everything here is also folded into `supabase/schema.sql`, which is
-- what a brand new project should run instead.
--
-- The Android app only ever uses the publishable (anon) key, so every write below has to be
-- expressible as a row level security policy. Never add a service_role key to the app.
--
-- What was broken
--   1. `rooms` had no DELETE policy, so the app could not roll back a half-created room and users
--      ended up with ghost lobbies after a failed slot insert.
--   2. The `room_slots` UPDATE policy used `using (auth.uid() = filled_by or filled_by is null)`,
--      which let any signed-in user grab a *local* seat of somebody else's room and let a joiner
--      overwrite a seat that had already been claimed.
--   3. `room_slots` had no INSERT policy in early installs, so `createRoom()` inserted the room row
--      and then failed on the slots.
--   4. The privileges (`grant`) for delete were missing, so even a correct policy could not run.

begin;

-- ---------------------------------------------------------------------------
-- 0. Safety net: the columns/constraints the policies below depend on.
-- ---------------------------------------------------------------------------

alter table public.rooms
  add column if not exists local_slots int not null default 1;
alter table public.rooms
  add column if not exists online_slots int not null default 1;

-- Slot ids must be generated by Postgres. The app inserts room slots *without* an `id` column
-- (see NewRoomSlotDto) so this default is what actually fills the primary key.
alter table public.room_slots
  alter column id set default gen_random_uuid();

alter table public.rooms enable row level security;
alter table public.room_slots enable row level security;
alter table public.games enable row level security;

-- ---------------------------------------------------------------------------
-- 1. Helper — is the caller the host of, or a seated player in, this room?
--    SECURITY DEFINER so that using it inside a room_slots policy cannot recurse into
--    the room_slots policies themselves.
-- ---------------------------------------------------------------------------

create or replace function public.is_room_host(target_room uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.rooms r
    where r.id = target_room and r.host_id = auth.uid()
  );
$$;

create or replace function public.is_room_participant(target_room uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.rooms r
    where r.id = target_room and r.host_id = auth.uid()
  ) or exists (
    select 1 from public.room_slots s
    where s.room_id = target_room and s.filled_by = auth.uid()
  );
$$;

-- Is `slot_index` an online (joinable) seat of this room? Local seats belong to the host device.
create or replace function public.is_online_slot(target_room uuid, target_index int)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.rooms r
    where r.id = target_room
      and target_index >= r.local_slots
      and target_index < r.total_slots
  );
$$;

grant execute on function public.is_room_host(uuid) to anon, authenticated;
grant execute on function public.is_room_participant(uuid) to anon, authenticated;
grant execute on function public.is_online_slot(uuid, int) to anon, authenticated;

-- ---------------------------------------------------------------------------
-- 2. rooms — host owns the row for its whole lifetime (insert, update, delete).
-- ---------------------------------------------------------------------------

drop policy if exists "Anyone can read rooms" on public.rooms;
create policy "Anyone can read rooms" on public.rooms
  for select using (true);

drop policy if exists "Authenticated users can create rooms" on public.rooms;
create policy "Authenticated users can create rooms" on public.rooms
  for insert to authenticated
  with check (
    auth.uid() = host_id
    and exists (select 1 from public.profiles p where p.id = auth.uid())
  );

drop policy if exists "Host can update own room" on public.rooms;
create policy "Host can update own room" on public.rooms
  for update to authenticated
  using (auth.uid() = host_id)
  with check (auth.uid() = host_id);

-- Lets the app clean up a room whose slots could not be created (deleteIncompleteRoom()).
drop policy if exists "Host can delete own room" on public.rooms;
create policy "Host can delete own room" on public.rooms
  for delete to authenticated
  using (auth.uid() = host_id);

-- ---------------------------------------------------------------------------
-- 3. room_slots — only the host creates seats; joiners may claim an EMPTY ONLINE seat.
-- ---------------------------------------------------------------------------

drop policy if exists "Anyone can read slots" on public.room_slots;
create policy "Anyone can read slots" on public.room_slots
  for select using (true);

drop policy if exists "Host can create room slots" on public.room_slots;
create policy "Host can create room slots" on public.room_slots
  for insert to authenticated
  with check (public.is_room_host(room_id));

-- The host device drives every local seat (names, ready flags, its own seat).
drop policy if exists "Host can manage room slots" on public.room_slots;
create policy "Host can manage room slots" on public.room_slots
  for update to authenticated
  using (public.is_room_host(room_id))
  with check (public.is_room_host(room_id));

-- A joiner may only take a seat that is (a) still empty and (b) an online seat, and may only
-- write their own uid into it. This is what stops two devices from stealing the same seat and
-- stops a joiner from occupying the host's local seats.
drop policy if exists "Users can claim/update their own slot" on public.room_slots;
drop policy if exists "Player can claim an empty online slot" on public.room_slots;
create policy "Player can claim an empty online slot" on public.room_slots
  for update to authenticated
  using (
    filled_by is null
    and public.is_online_slot(room_id, slot_index)
    and exists (select 1 from public.rooms r where r.id = room_id and r.status = 'lobby')
  )
  with check (filled_by = auth.uid());

-- Ready toggles: a player may update the seat they already own, and may not hand it to anybody
-- else (the WITH CHECK keeps `filled_by` pointing at the caller).
drop policy if exists "Player can update own slot" on public.room_slots;
create policy "Player can update own slot" on public.room_slots
  for update to authenticated
  using (filled_by = auth.uid())
  with check (filled_by = auth.uid());

drop policy if exists "Host can delete room slots" on public.room_slots;
create policy "Host can delete room slots" on public.room_slots
  for delete to authenticated
  using (public.is_room_host(room_id));

-- ---------------------------------------------------------------------------
-- 4. games — created by the host, updated by the players of that room only.
-- ---------------------------------------------------------------------------

drop policy if exists "Anyone involved can read games" on public.games;
create policy "Anyone involved can read games" on public.games
  for select using (true);

drop policy if exists "Authenticated users can create games" on public.games;
create policy "Authenticated users can create games" on public.games
  for insert to authenticated
  with check (public.is_room_host(room_id));

drop policy if exists "Anyone involved can update games" on public.games;
drop policy if exists "Room players can update games" on public.games;
create policy "Room players can update games" on public.games
  for update to authenticated
  using (room_id is not null and public.is_room_participant(room_id))
  with check (room_id is not null and public.is_room_participant(room_id));

-- ---------------------------------------------------------------------------
-- 5. Privileges. RLS still decides which rows each role may touch.
-- ---------------------------------------------------------------------------

grant usage on schema public to anon, authenticated;
grant select on public.profiles, public.rooms, public.room_slots, public.games to anon, authenticated;
grant select, insert, update on public.friends to authenticated;
grant insert, update on public.profiles, public.games to authenticated;
grant insert, update, delete on public.rooms, public.room_slots to authenticated;
revoke insert, update, delete on public.profiles, public.friends, public.rooms, public.room_slots, public.games from anon;

-- ---------------------------------------------------------------------------
-- 6. Indexes used by room lookup / lobby refresh.
-- ---------------------------------------------------------------------------

create unique index if not exists rooms_room_code_key on public.rooms (room_code);
create index if not exists rooms_code_passcode_idx on public.rooms (room_code, passcode);
create index if not exists room_slots_room_idx on public.room_slots (room_id, slot_index);
create index if not exists room_slots_filled_by_idx on public.room_slots (filled_by);
create index if not exists games_room_idx on public.games (room_id);

commit;

-- ---------------------------------------------------------------------------
-- 7. Realtime — the lobby and the shared board rely on these publications.
--    Kept outside the transaction so a duplicate entry cannot roll the fix back.
-- ---------------------------------------------------------------------------

do $$
begin
  alter publication supabase_realtime add table public.rooms;
exception when duplicate_object then null;
end $$;
do $$
begin
  alter publication supabase_realtime add table public.room_slots;
exception when duplicate_object then null;
end $$;
do $$
begin
  alter publication supabase_realtime add table public.games;
exception when duplicate_object then null;
end $$;
do $$
begin
  alter publication supabase_realtime add table public.profiles;
exception when duplicate_object then null;
end $$;

-- Realtime needs the full previous row to build UPDATE payloads for the lobby diff.
alter table public.rooms replica identity full;
alter table public.room_slots replica identity full;
alter table public.games replica identity full;
