package com.wordbattle.com.data.audio

import android.content.Context
import android.media.AudioAttributes
import android.media.MediaPlayer
import android.media.SoundPool
import androidx.annotation.RawRes
import com.wordbattle.com.R

/** Every one-shot effect the game can play. */
enum class GameSound(@RawRes val resId: Int, val volume: Float) {
    LETTER_PLACED(R.raw.snd_letter_place, 0.85f),
    WORD_SCORED(R.raw.snd_word_scored, 0.9f),
    TIMER_TICK(R.raw.snd_timer_tick, 0.5f),
    TIMER_WARNING(R.raw.snd_timer_warning, 0.75f),
    VICTORY(R.raw.snd_victory, 1f),
    DEFEAT(R.raw.snd_defeat, 0.8f)
}

/**
 * Central audio for the app: a [SoundPool] for short effects and a looping [MediaPlayer] for the
 * battle theme.
 *
 * All sounds are bundled WAV files generated by `tools/generate_sounds.py`, so playback works fully
 * offline. Everything is a no-op while [enabled] is false, and the object survives configuration
 * changes because it lives in `AppContainer`.
 */
class SoundManager(private val context: Context) {

    private val attributes = AudioAttributes.Builder()
        .setUsage(AudioAttributes.USAGE_GAME)
        .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
        .build()

    private val soundPool: SoundPool = SoundPool.Builder()
        .setMaxStreams(6)
        .setAudioAttributes(attributes)
        .build()

    private val soundIds = mutableMapOf<GameSound, Int>()
    private val loaded = mutableSetOf<Int>()
    private var themePlayer: MediaPlayer? = null
    private var themeShouldPlay = false

    /** Master switch mirrored from `MainUiState.soundEnabled`. */
    var enabled: Boolean = true
        set(value) {
            if (field == value) return
            field = value
            if (!value) {
                stopThemeInternal()
            } else if (themeShouldPlay) {
                startThemeInternal()
            }
        }

    init {
        soundPool.setOnLoadCompleteListener { _, sampleId, status ->
            if (status == 0) loaded += sampleId
        }
        GameSound.entries.forEach { sound ->
            runCatching { soundPool.load(context, sound.resId, 1) }
                .onSuccess { soundIds[sound] = it }
        }
    }

    /** Fire a one-shot effect. Silently ignored when sound is off or the sample is not ready. */
    fun play(sound: GameSound, rate: Float = 1f) {
        if (!enabled) return
        val id = soundIds[sound] ?: return
        if (id !in loaded) return
        val volume = sound.volume
        runCatching { soundPool.play(id, volume, volume, 1, 0, rate.coerceIn(0.5f, 2f)) }
    }

    /** Start (or resume) the looping battle theme. */
    fun startTheme() {
        themeShouldPlay = true
        if (enabled) startThemeInternal()
    }

    /** Stop the theme, e.g. when leaving the board. */
    fun stopTheme() {
        themeShouldPlay = false
        stopThemeInternal()
    }

    /** Duck the theme while a fanfare plays so the two do not fight each other. */
    fun setThemeVolume(volume: Float) {
        runCatching { themePlayer?.setVolume(volume, volume) }
    }

    fun release() {
        stopTheme()
        runCatching { soundPool.release() }
    }

    private fun startThemeInternal() {
        if (themePlayer?.isPlaying == true) return
        val player = themePlayer ?: runCatching {
            MediaPlayer.create(context, R.raw.music_theme)?.apply {
                isLooping = true
                setVolume(THEME_VOLUME, THEME_VOLUME)
            }
        }.getOrNull() ?: return
        themePlayer = player
        runCatching { player.start() }
    }

    private fun stopThemeInternal() {
        val player = themePlayer ?: return
        runCatching {
            if (player.isPlaying) player.pause()
            player.seekTo(0)
        }
    }

    companion object {
        const val THEME_VOLUME = 0.32f

        /** Volume the theme drops to while the victory fanfare is playing. */
        const val THEME_DUCKED_VOLUME = 0.08f
    }
}
